### ISSUE TITLE
Some roles are visible on 0.8.1 (Persists on 0.8.3.1b)

### ISSUE THREAD

**Issue by iChlorox** [music-discussion/TownOfHost-TheOtherRoles#44]
![image](https://user-images.githubusercontent.com/91646808/189459229-a7059eff-46fb-4f35-b581-34bd13a3050c.png)
![image](https://user-images.githubusercontent.com/91646808/189459506-e3914df8-2a2c-43d1-9d97-3590db4b7c3b.png)

**Comment by music-discussion** [comment]
This only happens if other people inside the game have the mod. While we do have support, it’s super broken.

**Comment by iChlorox** [comment]
Umm they were both on mobile

**Comment by iChlorox** [comment]
![image](https://user-images.githubusercontent.com/91646808/189471500-1b4ad26d-6667-4781-ba5c-73f820bd9abe.png)
Also doctor/investigator doesnt show properly on the host side! i had investigated green and blue and they were both green

**Comment by music-discussion** [comment]
again that only occurs when multiple people have the mod

**Comment by music-discussion** [comment]
actually. yea i fixed this

**Comment by The-LaughingMan** [comment]
This happens in a normal game as well. Sometimes when i join a normal un modded lobby.  Ill see one or two people with the title "crewmate" or in  rare cases "imposter" and i know who the imposter is already when im alive.

**Comment by Tommy-XL** [comment]
Maybe have been fixed in v0.8.3.1

**Comment by Tommy-XL** [comment]
Nope, This bug still exists
![image](https://user-images.githubusercontent.com/104814436/189620316-7a410fb7-fc8c-4b9c-8641-5f74e5824a74.png)

**Comment by Tommy-XL** [comment]
Нет, эта ошибка все еще существует

![Uploading photo_2022-09-12_16-16-14.jpg…]()

**Comment by Tommy-XL** [comment]
Нет, эта ошибка все еще существует

![photo_2022-09-12_16-16-14](https://user-images.githubusercontent.com/104814436/189620696-b4ec0929-78a2-47f2-8a77-7e2cbb04702a.jpg)

**Comment by music-discussion** [comment]
the only way to fix this is to just not show roles during meetings at all.

**Comment by music-discussion** [comment]
for host

**Comment by music-discussion** [comment]
those 3 roles u just said dont utilize the code for showing roles at all :/

**Comment by music-discussion** [comment]
fixed in 0.8.4
